// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GCloudiPhone
{
	public partial class PaymentTableViewCell : UITableViewCell
	{
		public PaymentTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
